language: csharp
dist: trusty

mono: none
dotnet: 1.0.1

cache:
  directories:
    - $HOME/.nuget/packages

branches:
  only:
    - master

script:
  - dotnet restore
  - dotnet build
  - dotnet test test/Nuhaven.Collections.Generic.Extensions.Tests/Nuhaven.Collections.Generic.Extensions.Tests.csproj
